### ISSUE TITLE
[Bug]: Log In redirects to host:8080 (Shopfast)

### ISSUE THREAD

**Issue by dawsonjb** [badger-advisor/madflow#111]
## Steps To Reproduce

1. If logged in, log out.
2. Go to the login page and complete.

## The current behavior
The login page redirects you to host:8080 which does not allow you to continue to the site. This problem is very severe.

## The expected behavior
After logging in you should stay on host:3000 to be able to use the system.

**Comment by jameszhang-a** [comment]
Gonna close later, since this is fixed already
